cluster  init
alibabacloud-automation/terraform-alicloud-hbase-cluster pull request #1
Opened 2020-02-12 03:10 UTC by joyken

cluster init

2020-02-13 07:09 UTC, zql-tqy commented on README-CN.md
> +本 Module 用于在阿里云的 VPC 下创建一个[HBase云数据库](https://help.aliyun.com/product/49055.html).
中文的README使用中文的标点

2020-02-13 07:09 UTC, zql-tqy commented on README-CN.md
> +本模板要求使用版本 Terraform 0.12.*
本模版要求使用 Terraform 0.12 和 阿里云 Provider 1.56.0+。（provider默认版本为1.56.0+）

2020-02-13 07:09 UTC, zql-tqy commented on README-CN.md
> +* 本 Module 使用的 AccessKey 和 SecretKey 可以直接从 `profile` 和 `shared_credentials_file` 中获取。如果未设置，可通过下载安装 [aliyun-cli](https://github.com/aliyun/aliyun-cli#installation) 后进行配置.
标点

2020-02-13 07:09 UTC, zql-tqy commented on README.md
> +This module requires Terraform 0.12.
The Module requires Terraform 0.12 and Terraform Provider AliCloud 1.56.0+.

2020-02-13 07:09 UTC, zql-tqy commented on README.md
> +You can use this in your terraform template with the following steps.
前面加上###空格

2020-02-13 07:09 UTC, zql-tqy commented on README.md
> +1. Adding a module resource to your template, e.g. main.tf
把1.去掉吧

2020-02-13 07:09 UTC, zql-tqy commented on examples/hbase-1.1/main.tf
> +  is_default = "true"
这个true不用加“”吧

2020-02-13 07:09 UTC, zql-tqy commented on modules/hbase-1.1/variables.tf
> +  description = "# one disk size, unit: GB, default 4 disk per core node; all disk size = coreNodeSize * 4 * core_disk_size(2 * 4 * 100 =800GB)"
这个#没用吧

2020-02-13 07:09 UTC, zql-tqy commented on modules/hbase-1.1/variables.tf
> +  description = "Whether to create HBase instance. If false, you can use a existing HBase instance by setting `existing_instance_id`."
把` 换成 '

2020-02-13 07:09 UTC, zql-tqy commented on modules/hbase-1.1/variables.tf
> +  description = "valid when pay_type = PrePaid"
先把参数描述清楚，再说明使用条件，下面的也是一样

2020-02-13 07:09 UTC, zql-tqy commented on modules/hbase-1.1/variables.tf
> +  default     = ""
把type都加上

2020-02-13 07:09 UTC, zql-tqy commented on modules/hbase-1.1/outputs.tf
> +  description = "the disk size of the core node. "
description的首字母统一都大写吧

2020-02-13 07:09 UTC, zql-tqy commented on README-CN.md
> +Terraform module which creates HBase instance resources on Alibaba Cloud
需要添加一个CHANGELOG.md文件，参考https://github.com/terraform-alicloud-modules/terraform-alicloud-rds-mysql/blob/master/CHANGELOG.md

2020-02-14 02:28 UTC, xiaozhu36 requested changes

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +  description = "The available zone to launch ecs instance and other resources."
描述不对

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +variable "engine" {
这个module已经限定了了engine，所以这个参数不用暴露，直接写死在main.tf中就行

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +  default     = "hbase.n1.medium"
这几个实例规格，如果要设置默认值，做好设置你们推荐的值

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +}
这些默认值也一样，按照你们推荐的或者标准的值来设置默认值

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +  description = "pay type, Valid value:PostPaid, PrePaid"
描述太简单了，要说清楚参数是干啥的

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +  description = "valid when pay_type = PrePaid"
这些也都一样

2020-02-14 02:28 UTC, xiaozhu36 commented on variables.tf
> +  description = "0 mean is_cold_storage = false."
首先要解释清楚参数的含义，接着说参数怎么使用

2020-02-14 02:28 UTC, xiaozhu36 commented on README.md
> +This module requires Terraform 0.12 and Terraform Provider AliCloud 1.56.0+.
后面的provider版本是支持了hbase的版本，也就是你的provider中写的available的值，肯定不是 1.56.0

2020-02-14 03:00 UTC, joyken commented on variables.tf
> +  default     = "hbase.n1.medium"
这个就是推荐的值。

2020-02-14 03:00 UTC, joyken commented on variables.tf
> +}
100 这个也是推荐的值， 和页面上默认的是一样的

2020-02-14 08:31 UTC, xiaozhu36 requested changes

2020-02-14 08:31 UTC, xiaozhu36 commented on README-CN.md
> +* [HBase 实例完整创建示例创建示例](https://github.com/terraform-alicloud-modules/terraform-alicloud-hbase-cluster/tree/master/examples/hbase)
这个没有改

2020-02-14 08:31 UTC, xiaozhu36 commented on examples/hbase-1.1/main.tf
> +  default = ""
example中region的default就不要设置为空

2020-02-14 08:31 UTC, xiaozhu36 commented on main.tf
> +  name                   = var.instance_name
这个地方要加一个是否创建的开关

2020-02-14 08:31 UTC, xiaozhu36 commented on variables.tf
> +variable "create_instance" {
这个参数应该用到控制是否创建instance上

2020-02-14 08:31 UTC, xiaozhu36 commented on variables.tf
> +variable "existing_instance_id" {
这个module中没有其他的resource，所以existing_instance_id可以直接去掉

2020-02-14 09:18 UTC, xiaozhu36 approved these changes

2020-02-14 09:18 UTC, merged